import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });
//TOKEN: 2b8962df668aa5c2cfa323029250ba97e6a6d7245aa19fde51a63ac12eead320
export const metadata: Metadata = {
  title: "Synapsis Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <StoreProvider>
          <main className="md:px-32 lg:px-64 px-16">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
